<?php
require __DIR__ . '/functions.php';
$quickAction = $_GET['action'] ?? '';
if ($quickAction === 'add' || $quickAction === 'minus') {
	$quickId = (int)($_GET['id'] ?? 0);
	if ($quickAction === 'add') add_to_cart($quickId);
	if ($quickAction === 'minus') { add_to_cart($quickId, 0); if (isset($_SESSION['cart'][$quickId])) { $_SESSION['cart'][$quickId]--; if ($_SESSION['cart'][$quickId] < 1) remove_from_cart($quickId); } }
	header('Location: index.php?view=cart'); exit;
}
if ($_SERVER['REQUEST_METHOD'] === 'POST') { check_csrf(); $action = $_POST['action'] ?? ''; $id = (int)($_POST['product_id'] ?? 0); if ($action === 'add') add_to_cart($id, (int)($_POST['quantity'] ?? 1)); if ($action === 'remove') remove_from_cart($id); header('Location: index.php?view=cart'); exit; }
$view = $_GET['view'] ?? 'shop'; $category = $_GET['category'] ?? ''; $query = $_GET['q'] ?? '';
$statement = db()->prepare('SELECT * FROM products WHERE active = 1 AND (? = "" OR category = ?) AND (name LIKE ? OR description LIKE ?) ORDER BY id DESC'); $like = "%$query%"; $statement->execute([$category, $category, $like, $like]); $products = $statement->fetchAll(); $lines = cart_products(); $subtotal = array_reduce($lines, fn($sum, $line) => $sum + ($line['price'] * $line['quantity']), 0); $delivery = 700; $shipping = $lines ? $delivery : 0;
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lissi | The everyday edit</title><link rel="stylesheet" href="style.css"></head><body>
<div class="announcement">Free delivery to your Bureau from 10,000 DA &nbsp; • &nbsp; Cash on delivery available</div><header class="header shell"><a class="brand" href="index.php"><img src="assets/logo.jpeg" alt="Lissi"><span>LISSI</span></a><nav class="nav"><a href="index.php">Shop all</a><a href="?category=Women">Women</a><a href="?category=Men">Men</a><a href="?category=Accessories">Accessories</a></nav><a class="bag" href="?view=cart">Bag (<?= cart_count() ?>)</a></header>
<?php if ($view === 'cart'): ?><section class="section shell"><p class="eyebrow">Your selection</p><h2>Your bag</h2><?php if (!$lines): ?><p>Your bag is waiting for something good. <a href="index.php">Continue shopping</a></p><?php else: ?><?php foreach ($lines as $line): ?><div class="line"><div class="art" style="background:<?= e($line['image_color']) ?>"><strong><?= e($line['short_name']) ?></strong></div><div><b><?= e($line['name']) ?></b><span><?= money($line['price']) ?></span><div class="step"><a href="?view=cart&action=minus&id=<?= $line['id'] ?>">−</a><span><?= $line['quantity'] ?></span><a href="?view=cart&action=add&id=<?= $line['id'] ?>">+</a><form method="post"><input type="hidden" name="csrf" value="<?= csrf() ?>"><input type="hidden" name="action" value="remove"><input type="hidden" name="product_id" value="<?= $line['id'] ?>"><button type="submit">Remove</button></form></div></div></div><?php endforeach; ?><div class="summary"><div><span>Subtotal</span><b><?= money($subtotal) ?></b></div><div><span>Delivery</span><b><?= money($shipping) ?></b></div><div class="total"><span>Total</span><b><?= money($subtotal + $shipping) ?></b></div><a class="dark" href="checkout.php">Checkout · COD →</a></div><?php endif; ?></section>
<?php else: ?><section class="hero shell"><div class="hero-copy"><p class="eyebrow">The everyday edit / 01</p><h1>Good things,<br><em>beautifully</em> chosen.</h1><p>Thoughtful pieces for the way you live now. Easy to love, made to last.</p><a class="dark" href="#catalog">Explore the edit ↓</a></div><div class="hero-art"></div></section><section id="catalog" class="section shell"><div class="section-head"><div><p class="eyebrow">Just in</p><h2>Find your everyday.</h2></div><div class="filters"><a class="<?= !$category ? 'active' : '' ?>" href="index.php">All</a><a class="<?= $category === 'Women' ? 'active' : '' ?>" href="?category=Women">Women</a><a class="<?= $category === 'Men' ? 'active' : '' ?>" href="?category=Men">Men</a><a class="<?= $category === 'Accessories' ? 'active' : '' ?>" href="?category=Accessories">Accessories</a></div></div><div class="grid"><?php foreach ($products as $product): ?><article class="card"><form method="post"><div class="art" style="background:<?= e($product['image_color']) ?>"><strong><?= e($product['short_name']) ?></strong><small><?= e($product['color']) ?></small></div><div class="meta"><div><b><?= e($product['name']) ?></b><span><?= e($product['category']) ?> · <?= e($product['sizes']) ?></span></div><b><?= money($product['price']) ?></b></div><div class="stock <?= $product['stock'] < 5 ? 'low' : '' ?>"><i></i><?= $product['stock'] < 5 ? 'Only ' . $product['stock'] . ' left' : 'In stock' ?></div><input type="hidden" name="csrf" value="<?= csrf() ?>"><input type="hidden" name="action" value="add"><input type="hidden" name="product_id" value="<?= $product['id'] ?>"><button class="dark" type="submit">Add to bag +</button></form></article><?php endforeach; ?></div></section><?php endif; ?><footer class="footer shell"><div><b>LISSI</b><p>Little things, thoughtfully chosen.</p></div><div><b>Need help?</b><p>hello@lissi.dz<br>Sat–Thu, 9am–6pm</p></div></footer></body></html>
